### ISSUE TITLE
Can the math.stackexchange crawler generalize easily to other stackexchange sites?

### ISSUE THREAD

**Issue by frogeyedpeas** [approach0/a0-crawlers#2]
It seems the only time it explicitly references the math.se sites are in the two lines:

root_url = "https://math.stackexchange.com"
file_prefix = 'mse'

**Comment by w32zhong** [comment]
I suppose so, I expect it to require just minor changes to be running for other SE sites. However, I am good to have more crawlers, but currently I have not enough resources and supports to put more data sources online, and also my current own focus is on some technical improvements.

**Comment by w32zhong** [comment]
I've recently generalized mse crawlers. Issue closed.

**Comment by frogeyedpeas** [comment]
"currently I have not enough resources and supports to put more data sources online" -- what type of resources do you need to start index say mathoverflow and physics.stackexchange.com?

**Comment by frogeyedpeas** [comment]
Would monetary resources be sufficient or do you need some extra development effort as well?

**Comment by w32zhong** [comment]
> "currently I have not enough resources and supports to put more data sources online" -- what type of resources do you need to start index say mathoverflow and physics.stackexchange.com?

@frogeyedpeas I mean hosting resources such as VPS or cloud service. Currently the hosting costs are covered by Linode. Unless I get other sponsorship or monetize this project, having more resources mean Approach Zero would run out of budget soon.

Development effort is not much at all to add data source, it is mainly about monetary resource.
