### ISSUE TITLE
Do you currently have a stored copy of the entire math.stackexchange set of questions and answer?

### ISSUE THREAD

**Issue by frogeyedpeas** [approach0/a0-crawlers#3]
How much money would it cost to have a copy of the entirety of math.se stored for document retrieval?

**Comment by w32zhong** [comment]
It really depends on how fast you want the search service to run and your operation infrastructure. I use 5 low-end VPS nodes for hosting MSE plus partial AoPS, I have all data source files as backup in a .gz tarball which is just around 1.6GB, it is not much at all.

If you are talking about MSE #post alone, I think it is well under 1.5 millions posts now, and you may need 2 to 3 low-end VPS nodes to host it and achieve query performance under 1 second in general (I am just guessing), if you do not consider other bookkeeping tasks (crawler, gateway, indexer etc.), the search service hosting cost alone is as low as 10 to 20 dollars per month.

**Comment by w32zhong** [comment]
issue closed due to no further follow-up.

**Comment by frogeyedpeas** [comment]
Interesting, I was asking because when I search $\delta_\lambda O$ in approach 0, the first pages of hits have no exact matches, however I had posted: https://math.stackexchange.com/questions/3963924/how-to-build-taylor-series-for-infinite-dimensional-objects which should lead to an exact match. So I figured that my post has not been indexed for some reason, and that motivated asking about how the posts are stored.

**Comment by w32zhong** [comment]
@frogeyedpeas Indeed, it has not been indexed since your post is very recent. However, I checked just now it has been crawled on the server, and you can search it after the next index update.
